# Generated by Django 2.1.15 on 2020-12-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0016_auto_20201202_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('track.product_track',),
        ),
    ]
