# Generated by Django 2.2.4 on 2020-08-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_track',
            name='user_id',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
