# Generated by Django 2.1.15 on 2020-09-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20200808_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_track',
            name='order_type',
            field=models.CharField(choices=[('abandon order', 'Abandon Order'), ('normal order', 'Normal Order'), ('recovered order', 'Recovered Order'), ('recoverable order', 'Recoverable Order')], default='Normal Order', max_length=18),
        ),
    ]
