# Generated by Django 2.1.15 on 2020-09-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_auto_20200930_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_track',
            name='order_type',
            field=models.CharField(choices=[('abandon order', 'Abandon Order'), ('normal order', 'Normal Order'), ('recovered order', 'Recovered Order'), ('recoverable order', 'Recoverable Order')], max_length=11),
        ),
    ]
