# Generated by Django 2.1.15 on 2020-10-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_product_track_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_track',
            name='order_type',
            field=models.CharField(default='Normal Order', max_length=18),
        ),
    ]
