# Generated by Django 2.1.15 on 2020-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_auto_20201002_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_track',
            name='product_view_count',
            field=models.IntegerField(default=0, max_length=7),
        ),
    ]
