# Generated by Django 2.1.15 on 2020-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_product_track_product_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_track',
            name='product_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
