# Generated by Django 2.1.15 on 2020-12-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0015_auto_20201006_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_track',
            old_name='ptrack_id',
            new_name='counter',
        ),
        migrations.RenameField(
            model_name='product_track',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='product_track',
            name='added_to_cart',
        ),
        migrations.RemoveField(
            model_name='product_track',
            name='checkout_initiated',
        ),
        migrations.RemoveField(
            model_name='product_track',
            name='order_confirmed',
        ),
        migrations.RemoveField(
            model_name='product_track',
            name='product_viewed',
        ),
        migrations.AddField(
            model_name='product_track',
            name='event',
            field=models.CharField(default='product_viewed', max_length=30),
        ),
        migrations.AddField(
            model_name='product_track',
            name='mob_no',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_track',
            name='user_status',
            field=models.CharField(default='product_viewed', max_length=30),
        ),
    ]
