# Generated by Django 2.1.15 on 2020-12-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0016_auto_20201202_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_track',
            name='user_status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
