# Generated by Django 2.1.15 on 2020-12-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0018_auto_20201203_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_detail',
            name='tracker_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product_track',
            name='merchant_id',
            field=models.BigIntegerField(),
        ),
    ]
