# Generated by Django 2.1.15 on 2020-12-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0019_auto_20201204_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_track',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
