# Generated by Django 2.2 on 2020-12-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0021_product_track_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_track',
            name='order_total',
            field=models.FloatField(default=0),
        ),
    ]
